# FF8 Memory Hook Configuration
# This file defines memory regions to copy and expand

[memory.K_MAGIC]
address = "0x01CF4064"
originalSize = 3420
newSize = 4096
copyAfter = "0x0047D343"
description = "K_MAGIC data structure - expanded for custom spells"
