[metadata]
script_version = "1.0.0"
memory_base = "0x01CF4064"
image_base = "0x00400000"
total_instructions = 67
description = "Instructions pré-patchées pour ff8_hook"

# Context configuration - read from the memory region created by the copy task
readFromContext = "ff8.magic.k_magic_data"

[instructions.0x0048D774]
bytes = "8D 86 XX XX XX XX"
offset = "0x2A"

[instructions.0x0048D8A4]
bytes = "8D 90 XX XX XX XX"
offset = "0x2A"

[instructions.0x00496C11]
bytes = "66 8B A8 XX XX XX XX"
offset = "0x28"

[instructions.0x00496AD9]
bytes = "8A 04 85 XX XX XX XX"
offset = "0x26"

[instructions.0x00496B0D]
bytes = "66 8B 0C 8D XX XX XX XX"
offset = "0x26"

[instructions.0x00496C1E]
bytes = "8A 90 XX XX XX XX"
offset = "0x25"

[instructions.0x00496A2D]
bytes = "8A 90 XX XX XX XX"
offset = "0x23"

[instructions.0x00496A23]
bytes = "84 90 XX XX XX XX"
offset = "0x22"

[instructions.0x00496983]
bytes = "8A 1C 95 XX XX XX XX"
offset = "0x21"

[instructions.0x0049694B]
bytes = "8A 0C 85 XX XX XX XX"
offset = "0x20"

[instructions.0x004965F3]
bytes = "8A 14 B5 XX XX XX XX"
offset = "0x1F"

[instructions.0x004967E3]
bytes = "8A 0C 95 XX XX XX XX"
offset = "0x1E"

[instructions.0x004968C3]
bytes = "8A 1C 95 XX XX XX XX"
offset = "0x1D"

[instructions.0x004965C2]
bytes = "8A 14 B5 XX XX XX XX"
offset = "0x1C"

[instructions.0x00496591]
bytes = "8A 14 B5 XX XX XX XX"
offset = "0x1B"

[instructions.0x0049655D]
bytes = "8A 14 B5 XX XX XX XX"
offset = "0x1A"

[instructions.0x00496529]
bytes = "8A 14 B5 XX XX XX XX"
offset = "0x19"

[instructions.0x004964A1]
bytes = "8A 1C 95 XX XX XX XX"
offset = "0x18"

[instructions.0x00496387]
bytes = "8A 0C 85 XX XX XX XX"
offset = "0x17"

[instructions.0x004900C4]
bytes = "8A 87 XX XX XX XX"
offset = "0x16"

[instructions.0x004900CF]
bytes = "66 8B 87 XX XX XX XX"
offset = "0x14"

[instructions.0x004900DC]
bytes = "8B 87 XX XX XX XX"
offset = "0x10"

[instructions.0x004900B9]
bytes = "8A 87 XX XX XX XX"
offset = "0xE"

[instructions.0x0048D731]
bytes = "8A 86 XX XX XX XX"
offset = "0xD"

[instructions.0x0048D7B9]
bytes = "8A 88 XX XX XX XX"
offset = "0xD"

[instructions.0x0048D89E]
bytes = "8A 88 XX XX XX XX"
offset = "0xD"

[instructions.0x0048DBDA]
bytes = "8A 88 XX XX XX XX"
offset = "0xD"

[instructions.0x0048FDB6]
bytes = "8A 14 B5 XX XX XX XX"
offset = "0xC"

[instructions.0x0048CB38]
bytes = "8A 89 XX XX XX XX"
offset = "0xB"

[instructions.0x004909B1]
bytes = "8A 88 XX XX XX XX"
offset = "0xB"

[instructions.0x00490A86]
bytes = "8A 88 XX XX XX XX"
offset = "0xB"

[instructions.0x004954E1]
bytes = "F6 81 XX XX XX XX 80"
offset = "0xB"

[instructions.0x004838CD]
bytes = "8A 04 B5 XX XX XX XX"
offset = "0xA"

[instructions.0x00483922]
bytes = "8A 0C B5 XX XX XX XX"
offset = "0xA"

[instructions.0x00483A30]
bytes = "8A 88 XX XX XX XX"
offset = "0xA"

[instructions.0x00483A6D]
bytes = "8A 88 XX XX XX XX"
offset = "0xA"

[instructions.0x00483ABC]
bytes = "8A 82 XX XX XX XX"
offset = "0xA"

[instructions.0x00483D99]
bytes = "84 98 XX XX XX XX"
offset = "0xA"

[instructions.0x00483DE0]
bytes = "84 98 XX XX XX XX"
offset = "0xA"

[instructions.0x00483E16]
bytes = "8A 88 XX XX XX XX"
offset = "0xA"

[instructions.0x00483E63]
bytes = "8A 8A XX XX XX XX"
offset = "0xA"

[instructions.0x00484EEB]
bytes = "8A 04 95 XX XX XX XX"
offset = "0xA"

[instructions.0x00484F0A]
bytes = "8A 14 8D XX XX XX XX"
offset = "0xA"

[instructions.0x00485C7F]
bytes = "8A 82 XX XX XX XX"
offset = "0xA"

[instructions.0x00489873]
bytes = "8A 14 8D XX XX XX XX"
offset = "0xA"

[instructions.0x0048A017]
bytes = "8A 0C 85 XX XX XX XX"
offset = "0xA"

[instructions.0x0048CB32]
bytes = "8A 91 XX XX XX XX"
offset = "0xA"

[instructions.0x00495510]
bytes = "8A 88 XX XX XX XX"
offset = "0xA"

[instructions.0x0048CB29]
bytes = "8A 91 XX XX XX XX"
offset = "0x9"

[instructions.0x00495520]
bytes = "8A 82 XX XX XX XX"
offset = "0x9"

[instructions.0x004909D7]
bytes = "8A 88 XX XX XX XX"
offset = "0x8"

[instructions.0x00490AAC]
bytes = "8A 88 XX XX XX XX"
offset = "0x8"

[instructions.0x004909DF]
bytes = "8A 90 XX XX XX XX"
offset = "0x7"

[instructions.0x00490AB4]
bytes = "8A 90 XX XX XX XX"
offset = "0x7"

[instructions.0x004F0647]
bytes = "8A 04 8D XX XX XX XX"
offset = "0x7"

[instructions.0x004F2EF1]
bytes = "8A 0C 85 XX XX XX XX"
offset = "0x7"

[instructions.0x004F71FD]
bytes = "8A 04 8D XX XX XX XX"
offset = "0x7"

[instructions.0x004909C9]
bytes = "8A 90 XX XX XX XX"
offset = "0x6"

[instructions.0x00490A9E]
bytes = "8A 90 XX XX XX XX"
offset = "0x6"

[instructions.0x004829F8]
bytes = "66 8B 0C 95 XX XX XX XX"
offset = "0x4"

[instructions.0x0048D737]
bytes = "66 8B 8E XX XX XX XX"
offset = "0x4"

[instructions.0x0048D7C3]
bytes = "66 8B 88 XX XX XX XX"
offset = "0x4"

[instructions.0x0048D8AE]
bytes = "66 8B 88 XX XX XX XX"
offset = "0x4"

[instructions.0x0048DBE0]
bytes = "66 8B 80 XX XX XX XX"
offset = "0x4"

[instructions.0x0047E9CF]
bytes = "66 8B 04 85 XX XX XX XX"
offset = "0x2"

[instructions.0x0047E97F]
bytes = "66 8B 04 85 XX XX XX XX"
offset = "0x0"
